server:
  port: 9090

spring:
  application:
    name: eureka-client

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:10099/eureka/
    healthcheck:
      enabled: true #开启健康检查（需要spring-boot-starter-actuator依赖）
  instance:
    leaseRenewalIntervalInSeconds: 10 #租期更新时间间隔（默认30秒）
    leaseExpirationDurationInSeconds: 30 #租期到期时间（默认90秒）